# ./harvester-install/vars_documentation.yml
---
# This file documents all variables used in the Harvester installation playbook

- name: Include variable documentation
  ansible.builtin.include_vars:
    file: vars_documentation.yml
  tags:
    - always
    - documentation

# PXE and Harvester configuration
pxe_harvester_version:
  description: "Version of Harvester to be installed"
  type: string
  example: "v1.3.1"

pxe_harvester_mgmt_interface:
  description: "Network interface for Harvester management"
  type: string
  example: "eno2"

pxe_harvester_vip:
  description: "Virtual IP for the Harvester cluster"
  type: string
  example: "10.0.20.20"

pxe_harvester_vip_mac:
  description: "MAC address associated with the virtual IP"
  type: string
  example: "da:50:09:ec:51:83"

pxe_harvester_osdisk:
  description: "Disk to be used for Harvester OS installation"
  type: string
  example: "/dev/disk/by-id/ata-KINGSTON_SA400S37240G_50026B7783F66D6B"

pxe_harvester_datadisk:
  description: "Disk to be used for Harvester data storage"
  type: string
  example: "/dev/disk/by-id/nvme-KINGSTON_SNV2S1000G_50026B77859C17C2"

# Network configuration
netmask:
  description: "Network mask for the Harvester network"
  type: string
  example: "255.255.255.0"

gateway:
  description: "Gateway IP address for the Harvester network"
  type: string
  example: "192.168.1.1"

dns_servers:
  description: "Comma-separated list of DNS servers"
  type: string
  example: "8.8.8.8,8.8.4.4"

ntp_servers:
  description: "Comma-separated list of NTP servers"
  type: string
  example: "0.suse.pool.ntp.org,1.suse.pool.ntp.org"

# SSH and authentication
ssh_public_key:
  description: "SSH public key for Harvester nodes"
  type: string
  example: "ssh-rsa AAAAB... your_public_key"

cluster_token:
  description: "Token for Harvester cluster authentication"
  type: string
  example: "your_cluster_token"

# Timeouts and retry counts
api_check_retries:
  description: "Number of retries for API availability check"
  type: integer
  example: 60

api_check_delay:
  description: "Delay between API availability check retries (in seconds)"
  type: integer
  example: 10

installation_timeout:
  description: "Timeout for the entire installation process (in seconds)"
  type: integer
  example: 3600

network_check_timeout:
  description: "Timeout for network connectivity checks (in seconds)"
  type: integer
  example: 60

# System requirements
min_disk_space:
  description: "Minimum required disk space in MB"
  type: integer
  example: 100000

min_network_bandwidth:
  description: "Minimum required network bandwidth in Mbps"
  type: integer
  example: 1000

max_network_latency:
  description: "Maximum acceptable network latency in ms"
  type: integer
  example: 20
